### ISSUE TITLE
JSON string error on Moodle 2.4

### ISSUE THREAD

**Issue by emdalton** [FMCorz/moodle-repository_evernote#1]
I installed and enabled the Evernote repository on a test server, but when I try to access the repository I get a popup JSON error and the following text appears instead of the Evernote folders:

Invalid JSON string<pre>array(1) { [" string(1493) ""utf-8" /> Evernote Error Evernote Oops, we encountered an error. Sorry, we've encountered an unexpected error. Terms of ServicePrivacy PolicyCopyright 2013 Evernote Corporation. All rights reserved. " } </pre>

Also, I had to use my own Evernote account to request an API Key. Would this grant users access to my Evernote account, or to their own evernote accounts?

**Comment by FMCorz** [comment]
Thanks for reporting this.

Before I investigate this, have you asked Evernote to make your API key valid on production servers ? If not, then you will have to ask them, see the readme file. In the meantime, if you have the key on the ''sandbox'' you can ''hack'' the file lib.php to use the sandbox (there is only one variable to change), and then create an account on the sandbox itself.

No, the API key will not give access to your account to anyone. It is linked to your account because they monitor the usage of the key, and if too important they might ignore some requests (the limits are pretty high, so don't worry).

Let me know how things are going.

Fred

**Comment by FMCorz** [comment]
I have investigated a bit, and it seems that your API key would be either incorrect or not available on the production servers. I have updated a new version of the repository to display a nicer error when this is the case. However, in order for this nice error to work, the issue https://tracker.moodle.org/browse/MDL-41630 to be integrated in Moodle first.
